
server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/approval
        username: thekim12
        password: 1234
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        show-sql: true
        open-in-view: true
        hibernate:
          ddl-auto: create
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          '[hibernate.format_sql]': true

    output:
      ansi:
        enabled: always
